use_frameworks!

source 'https://github.com/William500/WLMPrivateSpecs.git'
source 'https://github.com/Cocoapods/Specs.git'

target 'FRMImageCacheManager_Example' do
  pod 'FRMImageCacheManager', :path => '../'

  target 'FRMImageCacheManager_Tests' do
    inherit! :search_paths

    
  end
end
